### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by AbraaoAlves** [frontend-ce/fend-day-agenda#2]
# Tasks

- [x] https://github.com/frontend-ce/fend-day-agenda/issues/3
- [x] https://github.com/frontend-ce/fend-day-agenda/issues/7
- [x] https://github.com/frontend-ce/fend-day-agenda/issues/6
- [x] https://github.com/frontend-ce/fend-day-agenda/issues/8
- [ ] https://github.com/frontend-ce/fend-day-agenda/issues/14

## Screenshot
![Image](https://github.com/user-attachments/assets/eae172fa-8209-4cd2-ab3f-93635dd38c0f)
