### ISSUE TITLE
Api hook

### ISSUE THREAD

**Issue by AbraaoAlves** [frontend-ce/fend-day-agenda#35]
# Tasks

- [x] add react-query
- [x] create rest API service
- [ ] handle cache in localstorage

## Tests
- [ ] add msw to check stub data
